export async function GET() {
	return new Response(
		`
		<?xml version="1.0" encoding="UTF-8" ?>
		<urlset
			xmlns="https://www.sitemaps.org/schemas/sitemap/0.9"
			xmlns:xhtml="https://www.w3.org/1999/xhtml"
			xmlns:mobile="https://www.google.com/schemas/sitemap-mobile/1.0"
			xmlns:news="https://www.google.com/schemas/sitemap-news/0.9"
			xmlns:image="https://www.google.com/schemas/sitemap-image/1.1"
			xmlns:video="https://www.google.com/schemas/sitemap-video/1.1"
		>
			<url>
        <loc>https://www.championsqueue.gg</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>1.0</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/champions</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.5</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/champions/Caitlyn</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.5</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/matches</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.7</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/players</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.5</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/players/TL%20CoreJJ</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.5</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/teams</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.5</priority>
      </url>
      <url>
        <loc>https://www.championsqueue.gg/teams/Team%20Liquid%20Honda</loc>
        <lastmod>2024-10-05</lastmod>
        <changefreq>hourly</changefreq>
        <priority>0.5</priority>
      </url>
		</urlset>`.trim(),
		{
			headers: {
				'Content-Type': 'application/xml',
			},
		},
	);
}